# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_adding_contact_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddingContactWindow(object):
    def setupUi(self, AddingContactWindow):
        AddingContactWindow.setObjectName("AddingContactWindow")
        AddingContactWindow.resize(370, 208)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddingContactWindow)
        self.buttonBox.setGeometry(QtCore.QRect(180, 170, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(AddingContactWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_edit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_name.setObjectName("line_edit_name")
        self.verticalLayout.addWidget(self.line_edit_name)
        self.line_edit_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_phone.setText("")
        self.line_edit_phone.setObjectName("line_edit_phone")
        self.verticalLayout.addWidget(self.line_edit_phone)
        self.line_edit_birthday = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_birthday.setText("")
        self.line_edit_birthday.setObjectName("line_edit_birthday")
        self.verticalLayout.addWidget(self.line_edit_birthday)
        self.label_info = QtWidgets.QLabel(AddingContactWindow)
        self.label_info.setGeometry(QtCore.QRect(10, 170, 211, 31))
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")

        self.retranslateUi(AddingContactWindow)
        self.buttonBox.accepted.connect(AddingContactWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(AddingContactWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddingContactWindow)

    def retranslateUi(self, AddingContactWindow):
        _translate = QtCore.QCoreApplication.translate
        AddingContactWindow.setWindowTitle(_translate("AddingContactWindow", "Dialog"))
        self.line_edit_name.setPlaceholderText(_translate("AddingContactWindow", "Имя (только русские буквы)"))
        self.line_edit_phone.setPlaceholderText(_translate("AddingContactWindow", "Телефон"))
        self.line_edit_birthday.setPlaceholderText(_translate("AddingContactWindow", "Дата рождения (ГГГГ-ММ-ДД)"))
