# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_authorize_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorizeWindow(object):
    def setupUi(self, AuthorizeWindow):
        AuthorizeWindow.setObjectName("AuthorizeWindow")
        AuthorizeWindow.resize(291, 219)
        self.widget = QtWidgets.QWidget(AuthorizeWindow)
        self.widget.setGeometry(QtCore.QRect(10, 10, 274, 202))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_edit_username = QtWidgets.QLineEdit(self.widget)
        self.line_edit_username.setObjectName("line_edit_username")
        self.verticalLayout_2.addWidget(self.line_edit_username)
        self.line_edit_password = QtWidgets.QLineEdit(self.widget)
        self.line_edit_password.setObjectName("line_edit_password")
        self.verticalLayout_2.addWidget(self.line_edit_password)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_login = QtWidgets.QPushButton(self.widget)
        self.button_login.setObjectName("button_login")
        self.horizontalLayout.addWidget(self.button_login)
        self.button_registration = QtWidgets.QPushButton(self.widget)
        self.button_registration.setObjectName("button_registration")
        self.horizontalLayout.addWidget(self.button_registration)
        self.button_cancel = QtWidgets.QPushButton(self.widget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_box_remember = QtWidgets.QCheckBox(self.widget)
        self.check_box_remember.setObjectName("check_box_remember")
        self.verticalLayout.addWidget(self.check_box_remember)
        self.check_box_show_pasword = QtWidgets.QCheckBox(self.widget)
        self.check_box_show_pasword.setObjectName("check_box_show_pasword")
        self.verticalLayout.addWidget(self.check_box_show_pasword)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.button_reset_password = QtWidgets.QPushButton(self.widget)
        self.button_reset_password.setObjectName("button_reset_password")
        self.horizontalLayout_3.addWidget(self.button_reset_password)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(AuthorizeWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorizeWindow)

    def retranslateUi(self, AuthorizeWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorizeWindow.setWindowTitle(_translate("AuthorizeWindow", "Form"))
        self.line_edit_username.setPlaceholderText(_translate("AuthorizeWindow", "Имя пользователя"))
        self.line_edit_password.setPlaceholderText(_translate("AuthorizeWindow", "Пароль"))
        self.button_login.setText(_translate("AuthorizeWindow", "Войти"))
        self.button_registration.setText(_translate("AuthorizeWindow", "Регистрация"))
        self.button_cancel.setText(_translate("AuthorizeWindow", "Отмена"))
        self.check_box_remember.setText(_translate("AuthorizeWindow", "Запомнить"))
        self.check_box_show_pasword.setText(_translate("AuthorizeWindow", "Показать пароль"))
        self.button_reset_password.setText(_translate("AuthorizeWindow", "Забыли пароль"))
