# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_filling_contact_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FillingContactWindow(object):
    def setupUi(self, FillingContactWindow):
        FillingContactWindow.setObjectName("FillingContactWindow")
        FillingContactWindow.resize(370, 208)
        self.buttonBox = QtWidgets.QDialogButtonBox(FillingContactWindow)
        self.buttonBox.setGeometry(QtCore.QRect(180, 170, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(FillingContactWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_edit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_name.setObjectName("line_edit_name")
        self.verticalLayout.addWidget(self.line_edit_name)
        self.line_edit_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_phone.setText("")
        self.line_edit_phone.setObjectName("line_edit_phone")
        self.verticalLayout.addWidget(self.line_edit_phone)
        self.line_edit_birthday = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_edit_birthday.setText("")
        self.line_edit_birthday.setObjectName("line_edit_birthday")
        self.verticalLayout.addWidget(self.line_edit_birthday)
        self.label_info = QtWidgets.QLabel(FillingContactWindow)
        self.label_info.setGeometry(QtCore.QRect(10, 170, 211, 31))
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")

        self.retranslateUi(FillingContactWindow)
        self.buttonBox.accepted.connect(FillingContactWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(FillingContactWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FillingContactWindow)

    def retranslateUi(self, FillingContactWindow):
        _translate = QtCore.QCoreApplication.translate
        FillingContactWindow.setWindowTitle(_translate("FillingContactWindow", "Dialog"))
        self.line_edit_name.setPlaceholderText(_translate("FillingContactWindow", "Имя (только русские буквы)"))
        self.line_edit_phone.setPlaceholderText(_translate("FillingContactWindow", "Телефон"))
        self.line_edit_birthday.setPlaceholderText(_translate("FillingContactWindow", "Дата рождения (ГГГГ-ММ-ДД)"))
