# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 10, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.main_table = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table.setGeometry(QtCore.QRect(260, 100, 451, 191))
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(3)
        self.main_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(2, item)
        self.navigation_panel = QtWidgets.QListWidget(self.centralwidget)
        self.navigation_panel.setGeometry(QtCore.QRect(50, 110, 171, 191))
        self.navigation_panel.setObjectName("navigation_panel")
        item = QtWidgets.QListWidgetItem()
        self.navigation_panel.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.navigation_panel.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.navigation_panel.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.navigation_panel.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.navigation_panel.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "main window"))
        item = self.main_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.main_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.main_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.main_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.main_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.main_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Телефон"))
        item = self.main_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата рождения"))
        __sortingEnabled = self.navigation_panel.isSortingEnabled()
        self.navigation_panel.setSortingEnabled(False)
        item = self.navigation_panel.item(0)
        item.setText(_translate("MainWindow", "аб"))
        item = self.navigation_panel.item(1)
        item.setText(_translate("MainWindow", "вг"))
        item = self.navigation_panel.item(2)
        item.setText(_translate("MainWindow", "де"))
        item = self.navigation_panel.item(3)
        item.setText(_translate("MainWindow", "жз"))
        item = self.navigation_panel.item(4)
        item.setText(_translate("MainWindow", "ий"))
        self.navigation_panel.setSortingEnabled(__sortingEnabled)
