# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_reset_password_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPasswordWindow(object):
    def setupUi(self, ResetPasswordWindow):
        ResetPasswordWindow.setObjectName("ResetPasswordWindow")
        ResetPasswordWindow.resize(298, 211)
        self.widget = QtWidgets.QWidget(ResetPasswordWindow)
        self.widget.setGeometry(QtCore.QRect(40, 60, 218, 64))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_edit_email = QtWidgets.QLineEdit(self.widget)
        self.line_edit_email.setObjectName("line_edit_email")
        self.verticalLayout.addWidget(self.line_edit_email)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_change_password = QtWidgets.QPushButton(self.widget)
        self.button_change_password.setObjectName("button_change_password")
        self.horizontalLayout.addWidget(self.button_change_password)
        self.button_cancel = QtWidgets.QPushButton(self.widget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ResetPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ResetPasswordWindow)

    def retranslateUi(self, ResetPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ResetPasswordWindow.setWindowTitle(_translate("ResetPasswordWindow", "Form"))
        self.line_edit_email.setPlaceholderText(_translate("ResetPasswordWindow", "Адрес электронной почты"))
        self.button_change_password.setText(_translate("ResetPasswordWindow", "Сменить пароль"))
        self.button_cancel.setText(_translate("ResetPasswordWindow", "Отмена"))
